CREATE DATABASE api_sem_framework_db;

CREATE TABLE USERS (
  ID VARCHAR(50),
  NAME VARCHAR(255),
  USERNAME VARCHAR(255),
  EMAIL VARCHAR(255),
  PRIMARY KEY(ID)
);

ALTER TABLE USERS ADD PASSWORD VARCHAR(50) CHECK(LENGTH(PASSWORD) >= 8);

ALTER TABLE USERS ALTER COLUMN PASSWORD TYPE VARCHAR(200);